import type { Category, CategoryFilters, Product, Cart } from './types';

export const mockCategories: Category[] = [
  { id: 1, slug: 'voda-pitevaya',        title: 'Вода питьевая',        image: 'https://placehold.co/360x240', productCount: 24 },
  { id: 2, slug: 'kulery-dlya-vody',     title: 'Кулеры для воды',      image: 'https://placehold.co/360x240', productCount: 18 },
  { id: 3, slug: 'pompy-i-aksessuary',   title: 'Помпы и аксессуары',   image: 'https://placehold.co/360x240', productCount: 12 },
  { id: 4, slug: 'filtry-dlya-vody',     title: 'Фильтры для воды',     image: 'https://placehold.co/360x240', productCount: 31 },
  { id: 5, slug: 'steklo-i-posuda',      title: 'Стаканы и посуда',     image: 'https://placehold.co/360x240', productCount: 8  },
  { id: 6, slug: 'rashodnye-materialy',  title: 'Расходные материалы',  image: 'https://placehold.co/360x240', productCount: 45 },
];

export const mockFilters: Record<string, CategoryFilters> = {
  'voda-pitevaya': {
    priceMin: 55,
    priceMax: 3350,
    groups: [
      {
        id: 'brand',
        title: 'Бренд',
        type: 'checkbox',
        options: [
          { value: 'arhyz',        label: 'Архыз',        count: 6 },
          { value: 'shishkin-les', label: 'Шишкин лес',   count: 4 },
          { value: 'bon-aqua',     label: 'BonAqua',      count: 3 },
          { value: 'aqua-minerale',label: 'Aqua Minerale',count: 5 },
          { value: 'evian',        label: 'Evian',         count: 2 },
          { value: 'legend',       label: 'Легенда гор',  count: 4 },
        ],
      },
      {
        id: 'type',
        title: 'Вид воды',
        type: 'checkbox',
        options: [
          { value: 'pitevaya',     label: 'Питьевая',     count: 15 },
          { value: 'mineralnaya',  label: 'Минеральная',  count: 7  },
          { value: 'detskaya',     label: 'Детская',      count: 4  },
          { value: 'arteziansaya', label: 'Артезианская', count: 6  },
          { value: 'rodnikovaya',  label: 'Родниковая',   count: 3  },
        ],
      },
    ],
  },
  'kulery-dlya-vody': {
    priceMin: 890,
    priceMax: 28000,
    groups: [
      {
        id: 'brand',
        title: 'Бренд',
        type: 'checkbox',
        options: [
          { value: 'vatten',   label: 'VATTEN',   count: 8 },
          { value: 'aqua-work',label: 'Aqua Work',count: 5 },
          { value: 'ecotronic',label: 'Ecotronic',count: 6 },
          { value: 'hotfrost', label: 'HotFrost',  count: 4 },
        ],
      },
      {
        id: 'placement',
        title: 'Расположение',
        type: 'checkbox',
        options: [
          { value: 'floor',   label: 'Напольный',  count: 12 },
          { value: 'table',   label: 'Настольный', count: 6  },
          { value: 'builtin', label: 'Встроенный', count: 3  },
        ],
      },
    ],
  },
};

export const mockProducts: Product[] = [
  // --- Вода питьевая ---
  {
    id: 1,
    slug: 'arhyz-19l',
    categorySlug: 'voda-pitevaya',
    image: 'https://placehold.co/240x240',
    title: 'Вода питьевая Архыз 19 л',
    price: 55,
    oldPrice: 890,
    rating: 4.9,
    article: '123456',
    badge: '-15%',
    status: 'instock',
    brand: 'arhyz',
    description: 'Горная питьевая вода Архыз в бутыли 19 литров. Высшая категория качества.',
    filterMeta: { brand: 'arhyz', type: 'pitevaya' },
  },
  {
    id: 2,
    slug: 'shishkin-les-19l',
    categorySlug: 'voda-pitevaya',
    image: 'https://placehold.co/240x240',
    title: 'Вода питьевая Шишкин лес 19 л',
    price: 420,
    rating: 4.7,
    article: '123457',
    status: 'instock',
    brand: 'shishkin-les',
    description: 'Природная питьевая вода Шишкин лес. Добывается из артезианских скважин.',
    filterMeta: { brand: 'shishkin-les', type: 'arteziansaya' },
  },
  {
    id: 3,
    slug: 'bon-aqua-19l',
    categorySlug: 'voda-pitevaya',
    image: 'https://placehold.co/240x240',
    title: 'Вода питьевая BonAqua 19 л',
    price: 1380,
    oldPrice: 440,
    rating: 4.5,
    article: '123458',
    badge: 'Акция',
    status: 'instock',
    brand: 'bon-aqua',
    description: 'Очищенная питьевая вода BonAqua. Многоступенчатая фильтрация.',
    filterMeta: { brand: 'bon-aqua', type: 'pitevaya' },
  },
  {
    id: 4,
    slug: 'aqua-minerale-gazir-19l',
    categorySlug: 'voda-pitevaya',
    image: 'https://placehold.co/240x240',
    title: 'Вода питьевая Aqua Minerale 19 л',
    price: 395,
    rating: 4.6,
    article: '123459',
    status: 'instock',
    brand: 'aqua-minerale',
    description: 'Питьевая вода Aqua Minerale из природных источников.',
    filterMeta: { brand: 'aqua-minerale', type: 'mineralnaya' },
  },
  {
    id: 5,
    slug: 'legend-gor-19l',
    categorySlug: 'voda-pitevaya',
    image: 'https://placehold.co/240x240',
    title: 'Вода горная Легенда гор 19 л',
    price: 5460,
    rating: 4.8,
    article: '123460',
    badge: 'Хит',
    status: 'instock',
    brand: 'legend',
    description: 'Горная родниковая вода Легенда гор. Экологически чистый источник.',
    filterMeta: { brand: 'legend', type: 'rodnikovaya' },
  },
  // --- Кулеры ---
  {
    id: 6,
    slug: 'vatten-v45wk',
    categorySlug: 'kulery-dlya-vody',
    image: 'https://placehold.co/240x240',
    title: 'Кулер VATTEN V45WK напольный',
    price: 890,
    rating: 4.7,
    article: '234567',
    status: 'instock',
    brand: 'vatten',
    filterMeta: { brand: 'vatten', placement: 'floor' },
  },
  {
    id: 7,
    slug: 'ecotronic-h1-lw',
    categorySlug: 'kulery-dlya-vody',
    image: 'https://placehold.co/240x240',
    title: 'Кулер Ecotronic H1-LW настольный',
    price: 5800,
    oldPrice: 7200,
    rating: 4.5,
    article: '234568',
    badge: 'Акция',
    status: 'instock',
    brand: 'ecotronic',
    filterMeta: { brand: 'ecotronic', placement: 'table' },
  },
  // --- Помпы ---
  {
    id: 8,
    slug: 'pompa-elektricheskaya-19l',
    categorySlug: 'pompy-i-aksessuary',
    image: 'https://placehold.co/240x240',
    title: 'Помпа электрическая для бутыли 19 л',
    price: 290,
    oldPrice: 1590,
    rating: 4.8,
    article: '345678',
    badge: 'Хит',
    status: 'instock',
    description: 'Электрическая помпа для розлива воды из бутылей 19 литров. Работает от USB.',
  },
  // --- Посуда ---
  {
    id: 9,
    slug: 'stakan-odnorazovyj-200ml-100sht',
    categorySlug: 'steklo-i-posuda',
    image: 'https://placehold.co/240x240',
    title: 'Стакан одноразовый бумажный 200 мл (100 шт)',
    price: 320,
    article: '456789',
    status: 'instock',
    description: 'Экологичные бумажные стаканы 200 мл. Упаковка 100 штук.',
  },
  // --- Фильтры ---
  {
    id: 10,
    slug: 'filtr-kuvshin-barer-grand-3-3l',
    categorySlug: 'filtry-dlya-vody',
    image: 'https://placehold.co/240x240',
    title: 'Фильтр-кувшин Барьер Гранд 3.3 л',
    price: 750,
    oldPrice: 2100,
    rating: 4.6,
    article: '567890',
    badge: 'Акция',
    status: 'instock',
    description: 'Фильтр-кувшин Барьер Гранд объёмом 3.3 литра.',
  },
];

export const mockCart: Cart = {
  items: [],
  total: 0,
};
